################################################################################
#
# gnuradio
#
################################################################################

GNURADIO_SOAPY_VERSION = 3.10.12.0
GNURADIO_SOAPY_SITE = $(call github,gnuradio,gnuradio,v$(GNURADIO_SOAPY_VERSION))
GNURADIO_SOAPY_LICENSE = GPL-3.0+
GNURADIO_SOAPY_LICENSE_FILES = COPYING

GNURADIO_SOAPY_SUPPORTS_IN_SOURCE_BUILD = NO

GNURADIO_SOAPY_DEPENDENCIES = \
	host-python3 \
	boost \
	log4cpp \
	gmp \
	spdlog \
	volk

GNURADIO_SOAPY_CONF_OPTS = \
	-DPYTHON_EXECUTABLE=$(HOST_DIR)/bin/python3 \
	-DENABLE_DEFAULT=OFF \
	-DENABLE_EXAMPLES=OFF \
	-DENABLE_GNURADIO_RUNTIME=ON \
	-DENABLE_TESTING=OFF \
	-DXMLTO_EXECUTABLE=NOTFOUND

# For third-party blocks, the gnuradio libraries are mandatory at
# compile time.
GNURADIO_SOAPY_INSTALL_STAGING = YES

ifeq ($(BR2_TOOLCHAIN_HAS_LIBATOMIC),y)
GNURADIO_SOAPY_CONF_OPTS += -DCMAKE_EXE_LINKER_FLAGS=-latomic
endif

ifeq ($(BR2_PACKAGE_GNURADIO_SOAPY_ANALOG),y)
GNURADIO_SOAPY_CONF_OPTS += -DENABLE_GR_ANALOG=ON
else
GNURADIO_SOAPY_CONF_OPTS += -DENABLE_GR_ANALOG=OFF
endif

ifeq ($(BR2_PACKAGE_GNURADIO_SOAPY_AUDIO),y)
ifeq ($(BR2_PACKAGE_ALSA_LIB),y)
GNURADIO_SOAPY_DEPENDENCIES += alsa-lib
endif
ifeq ($(BR2_PACKAGE_PORTAUDIO),y)
GNURADIO_SOAPY_DEPENDENCIES += portaudio
endif
GNURADIO_SOAPY_CONF_OPTS += -DENABLE_GR_AUDIO=ON
else
GNURADIO_SOAPY_CONF_OPTS += -DENABLE_GR_AUDIO=OFF
endif

ifeq ($(BR2_PACKAGE_GNURADIO_SOAPY_BLOCKS),y)
GNURADIO_SOAPY_CONF_OPTS += -DENABLE_GR_BLOCKS=ON
ifeq ($(BR2_PACKAGE_LIBSNDFILE),y)
GNURADIO_SOAPY_DEPENDENCIES += libsndfile
endif
else
GNURADIO_SOAPY_CONF_OPTS += -DENABLE_GR_BLOCKS=OFF
endif

ifeq ($(BR2_PACKAGE_GNURADIO_SOAPY_CHANNELS),y)
GNURADIO_SOAPY_CONF_OPTS += -DENABLE_GR_CHANNELS=ON
else
GNURADIO_SOAPY_CONF_OPTS += -DENABLE_GR_CHANNELS=OFF
endif

ifeq ($(BR2_PACKAGE_GNURADIO_SOAPY_CTRLPORT),y)
GNURADIO_SOAPY_CONF_OPTS += -DENABLE_GR_CTRLPORT=ON
else
GNURADIO_SOAPY_CONF_OPTS += -DENABLE_GR_CTRLPORT=OFF
endif

ifeq ($(BR2_PACKAGE_GNURADIO_SOAPY_DIGITAL),y)
GNURADIO_SOAPY_CONF_OPTS += -DENABLE_GR_DIGITAL=ON
else
GNURADIO_SOAPY_CONF_OPTS += -DENABLE_GR_DIGITAL=OFF
endif

ifeq ($(BR2_PACKAGE_GNURADIO_SOAPY_DTV),y)
GNURADIO_SOAPY_CONF_OPTS += -DENABLE_GR_DTV=ON
else
GNURADIO_SOAPY_CONF_OPTS += -DENABLE_GR_DTV=OFF
endif

ifeq ($(BR2_PACKAGE_GNURADIO_SOAPY_FEC),y)
GNURADIO_SOAPY_DEPENDENCIES += gsl
GNURADIO_SOAPY_CONF_OPTS += -DENABLE_GR_FEC=ON
else
GNURADIO_SOAPY_CONF_OPTS += -DENABLE_GR_FEC=OFF
endif

ifeq ($(BR2_PACKAGE_GNURADIO_SOAPY_FFT),y)
GNURADIO_SOAPY_DEPENDENCIES += fftw-single
GNURADIO_SOAPY_CONF_OPTS += -DENABLE_GR_FFT=ON
else
GNURADIO_SOAPY_CONF_OPTS += -DENABLE_GR_FFT=OFF
endif

ifeq ($(BR2_PACKAGE_GNURADIO_SOAPY_FILTER),y)
GNURADIO_SOAPY_CONF_OPTS += -DENABLE_GR_FILTER=ON
else
GNURADIO_SOAPY_CONF_OPTS += -DENABLE_GR_FILTER=OFF
endif

ifeq ($(BR2_PACKAGE_GNURADIO_SOAPY_NETWORK),y)
GNURADIO_SOAPY_CONF_OPTS += -DENABLE_GR_NETWORK=ON
else
GNURADIO_SOAPY_CONF_OPTS += -DENABLE_GR_NETWORK=OFF
endif

ifeq ($(BR2_PACKAGE_GNURADIO_SOAPY_IIO),y)
GNURADIO_SOAPY_CONF_OPTS += -DENABLE_GR_IIO=ON
GNURADIO_SOAPY_DEPENDENCIES += libiio
else
GNURADIO_SOAPY_CONF_OPTS += -DENABLE_GR_IIO=OFF
endif

ifeq ($(BR2_PACKAGE_GNURADIO_SOAPY_PYTHON),y)
GNURADIO_SOAPY_DEPENDENCIES += python3 python-pybind \
	host-python-numpy host-python-packaging
GNURADIO_SOAPY_CONF_OPTS += -DENABLE_PYTHON=ON
# mandatory to avoid pybind11 to overwrite variables provided
# by gnuradio and buildroot
GNURADIO_SOAPY_CONF_OPTS += -DPYBIND11_PYTHONLIBS_OVERWRITE=OFF
# mandatory to avoid pybind11 to force libraries extensions
# with a name based on host architecture
GNURADIO_SOAPY_CONF_ENV += _PYTHON_SYSCONFIGDATA_NAME="$(PKG_PYTHON_SYSCONFIGDATA_NAME)" \
	PYTHONPATH=$(PYTHON3_PATH)
# mandatory to install python modules in site-packages and to use
# correct path for python libraries
GNURADIO_SOAPY_CONF_OPTS += -DGR_PYTHON_RELATIVE=ON \
	-DGR_PYTHON_DIR=lib/python$(PYTHON3_VERSION_MAJOR)/site-packages
else
GNURADIO_SOAPY_CONF_OPTS += -DENABLE_PYTHON=OFF
endif

ifeq ($(BR2_PACKAGE_GNURADIO_SOAPY_QTGUI),y)
GNURADIO_SOAPY_DEPENDENCIES += qt5base python-pyqt5 qwt
GNURADIO_SOAPY_CONF_OPTS += -DENABLE_GR_QTGUI=ON
else
GNURADIO_SOAPY_CONF_OPTS += -DENABLE_GR_QTGUI=OFF
endif

ifeq ($(BR2_PACKAGE_GNURADIO_SOAPY_SOAPY),y)
GNURADIO_SOAPY_DEPENDENCIES += soapy-sdr
GNURADIO_SOAPY_CONF_OPTS += -DENABLE_GR_SOAPY=ON
else
GNURADIO_SOAPY_CONF_OPTS += -DENABLE_GR_SOAPY=OFF
endif

ifeq ($(BR2_PACKAGE_GNURADIO_SOAPY_TRELLIS),y)
GNURADIO_SOAPY_CONF_OPTS += -DENABLE_GR_TRELLIS=ON
else
GNURADIO_SOAPY_CONF_OPTS += -DENABLE_GR_TRELLIS=OFF
endif

ifeq ($(BR2_PACKAGE_GNURADIO_SOAPY_UHD),y)
GNURADIO_SOAPY_DEPENDENCIES += uhd
GNURADIO_SOAPY_CONF_OPTS += -DENABLE_GR_UHD=ON
else
GNURADIO_SOAPY_CONF_OPTS += -DENABLE_GR_UHD=OFF
endif

ifeq ($(BR2_PACKAGE_GNURADIO_SOAPY_UTILS),y)
GNURADIO_SOAPY_CONF_OPTS += -DENABLE_GR_UTILS=ON
else
GNURADIO_SOAPY_CONF_OPTS += -DENABLE_GR_UTILS=OFF
endif

ifeq ($(BR2_PACKAGE_GNURADIO_SOAPY_ZEROMQ),y)
GNURADIO_SOAPY_DEPENDENCIES += cppzmq
ifeq ($(BR2_PACKAGE_GNURADIO_SOAPY_PYTHON),y)
GNURADIO_SOAPY_DEPENDENCIES += python-pyzmq
endif
GNURADIO_SOAPY_CONF_OPTS += -DENABLE_GR_ZEROMQ=ON
else
GNURADIO_SOAPY_CONF_OPTS += -DENABLE_GR_ZEROMQ=OFF
endif

$(eval $(cmake-package))
